Shader "AVProVideo/IMGUI/Texture Transparent" {
	Properties {
		_MainTex ("Texture", any) = "" {}
		_ChromaTex ("Chroma", any) = "" {}
		_VertScale ("Vertical Scale", Range(-1, 1)) = 1
		[KeywordEnum(None, Top_Bottom, Left_Right)] AlphaPack ("Alpha Pack", Float) = 0
		[Toggle(APPLY_GAMMA)] _ApplyGamma ("Apply Gamma", Float) = 0
		[Toggle(USE_YPCBCR)] _UseYpCbCr ("Use YpCbCr", Float) = 0
	}
	SubShader {
		Tags { "ForceSupported" = "true" "RenderType" = "Overlay" }
		Pass {
			Tags { "ForceSupported" = "true" "RenderType" = "Overlay" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 33576
			Program "vp" {
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _VertScale          c9       1
					//
					
					    vs_3_0
					    def c10, 1, 0, -2, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c10.xxxy, c10.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov o1, v1
					    mov r0.y, c10.y
					    slt r0.x, c9.x, r0.y
					    mad r1.xy, v2, c8, c8.zwzw
					    mad r0.y, r1.y, c10.z, c10.x
					    mad r1.z, r0.x, r0.y, r1.y
					    mov o2, r1.xzxz
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 18 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mad r1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.y, -r1.y, l(1.000000)
					movc r1.z, r0.x, r0.y, r1.y
					mov o2.xyzw, r1.xzxz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _VertScale          c9       1
					//
					
					    vs_3_0
					    def c10, 1, 0, -2, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c10.xxxy, c10.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov o1, v1
					    mov r0.y, c10.y
					    slt r0.x, c9.x, r0.y
					    mad r1.xy, v2, c8, c8.zwzw
					    mad r0.y, r1.y, c10.z, c10.x
					    mad r1.z, r0.x, r0.y, r1.y
					    mov o2, r1.xzxz
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 18 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mad r1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.y, -r1.y, l(1.000000)
					movc r1.z, r0.x, r0.y, r1.y
					mov o2.xyzw, r1.xzxz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _VertScale          c9       1
					//
					
					    vs_3_0
					    def c10, 1, 0, -2, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c10.xxxy, c10.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov o1, v1
					    mov r0.y, c10.y
					    slt r0.x, c9.x, r0.y
					    mad r1.xy, v2, c8, c8.zwzw
					    mad r0.y, r1.y, c10.z, c10.x
					    mad r1.z, r0.x, r0.y, r1.y
					    mov o2, r1.xzxz
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 18 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mad r1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.y, -r1.y, l(1.000000)
					movc r1.z, r0.x, r0.y, r1.y
					mov o2.xyzw, r1.xzxz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _VertScale          c9       1
					//
					
					    vs_3_0
					    def c10, 1, 0, -2, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c10.xxxy, c10.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov o1, v1
					    mov r0.y, c10.y
					    slt r0.x, c9.x, r0.y
					    mad r1.xy, v2, c8, c8.zwzw
					    mad r0.y, r1.y, c10.z, c10.x
					    mad r1.z, r0.x, r0.y, r1.y
					    mov o2, r1.xzxz
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 18 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mad r1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.y, -r1.y, l(1.000000)
					movc r1.z, r0.x, r0.y, r1.y
					mov o2.xyzw, r1.xzxz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _MainTex_TexelSize  c9       1
					//   _VertScale          c10      1
					//
					
					    vs_3_0
					    def c11, 1, 0, 1.5, 0.5
					    def c12, -3, 0.5, 0, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c11.xxxy, c11.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov o1, v1
					    mov r0.yz, c11
					    slt r0.x, c10.x, r0.y
					    mul r0.y, r0.z, c9.y
					    mov r1.y, c9.y
					    mad r0.z, r1.y, c12.x, c12.y
					    mad r1.xy, v2, c8, c8.zwzw
					    mad r0.z, r1.y, r0.z, r0.y
					    add r0.w, r0.z, c11.w
					    add r0.y, -r0.z, -r0.w
					    add r0.y, r0.y, c11.x
					    mad r1.zw, r0.x, r0.y, r0
					    mov o2, r1.xzxw
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 24 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mul r0.y, cb0[3].y, l(1.500000)
					mad r0.z, cb0[3].y, l(-3.000000), l(0.500000)
					mad r1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r0.z, r1.y, r0.z, r0.y
					add r0.w, r0.z, l(0.500000)
					add r2.xy, -r0.wzww, l(1.000000, 1.000000, 0.000000, 0.000000)
					movc r1.zw, r0.xxxx, r2.xxxy, r0.zzzw
					mov o2.xyzw, r1.xzxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _MainTex_TexelSize  c9       1
					//   _VertScale          c10      1
					//
					
					    vs_3_0
					    def c11, 1, 0, 1.5, 0.5
					    def c12, -3, 0.5, 0, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c11.xxxy, c11.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov o1, v1
					    mov r0.yz, c11
					    slt r0.x, c10.x, r0.y
					    mul r0.y, r0.z, c9.y
					    mov r1.y, c9.y
					    mad r0.z, r1.y, c12.x, c12.y
					    mad r1.xy, v2, c8, c8.zwzw
					    mad r0.z, r1.y, r0.z, r0.y
					    add r0.w, r0.z, c11.w
					    add r0.y, -r0.z, -r0.w
					    add r0.y, r0.y, c11.x
					    mad r1.zw, r0.x, r0.y, r0
					    mov o2, r1.xzxw
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 24 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mul r0.y, cb0[3].y, l(1.500000)
					mad r0.z, cb0[3].y, l(-3.000000), l(0.500000)
					mad r1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r0.z, r1.y, r0.z, r0.y
					add r0.w, r0.z, l(0.500000)
					add r2.xy, -r0.wzww, l(1.000000, 1.000000, 0.000000, 0.000000)
					movc r1.zw, r0.xxxx, r2.xxxy, r0.zzzw
					mov o2.xyzw, r1.xzxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _MainTex_TexelSize  c9       1
					//   _VertScale          c10      1
					//
					
					    vs_3_0
					    def c11, 1, 0, 1.5, 0.5
					    def c12, -3, 0.5, 0, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c11.xxxy, c11.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov o1, v1
					    mov r0.yz, c11
					    slt r0.x, c10.x, r0.y
					    mul r0.y, r0.z, c9.y
					    mov r1.y, c9.y
					    mad r0.z, r1.y, c12.x, c12.y
					    mad r1.xy, v2, c8, c8.zwzw
					    mad r0.z, r1.y, r0.z, r0.y
					    add r0.w, r0.z, c11.w
					    add r0.y, -r0.z, -r0.w
					    add r0.y, r0.y, c11.x
					    mad r1.zw, r0.x, r0.y, r0
					    mov o2, r1.xzxw
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 24 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mul r0.y, cb0[3].y, l(1.500000)
					mad r0.z, cb0[3].y, l(-3.000000), l(0.500000)
					mad r1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r0.z, r1.y, r0.z, r0.y
					add r0.w, r0.z, l(0.500000)
					add r2.xy, -r0.wzww, l(1.000000, 1.000000, 0.000000, 0.000000)
					movc r1.zw, r0.xxxx, r2.xxxy, r0.zzzw
					mov o2.xyzw, r1.xzxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _MainTex_TexelSize  c9       1
					//   _VertScale          c10      1
					//
					
					    vs_3_0
					    def c11, 1, 0, 1.5, 0.5
					    def c12, -3, 0.5, 0, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c11.xxxy, c11.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov o1, v1
					    mov r0.yz, c11
					    slt r0.x, c10.x, r0.y
					    mul r0.y, r0.z, c9.y
					    mov r1.y, c9.y
					    mad r0.z, r1.y, c12.x, c12.y
					    mad r1.xy, v2, c8, c8.zwzw
					    mad r0.z, r1.y, r0.z, r0.y
					    add r0.w, r0.z, c11.w
					    add r0.y, -r0.z, -r0.w
					    add r0.y, r0.y, c11.x
					    mad r1.zw, r0.x, r0.y, r0
					    mov o2, r1.xzxw
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 24 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 3
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mul r0.y, cb0[3].y, l(1.500000)
					mad r0.z, cb0[3].y, l(-3.000000), l(0.500000)
					mad r1.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					mad r0.z, r1.y, r0.z, r0.y
					add r0.w, r0.z, l(0.500000)
					add r2.xy, -r0.wzww, l(1.000000, 1.000000, 0.000000, 0.000000)
					movc r1.zw, r0.xxxx, r2.xxxy, r0.zzzw
					mov o2.xyzw, r1.xzxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _MainTex_TexelSize  c9       1
					//   _VertScale          c10      1
					//
					
					    vs_3_0
					    def c11, 1, 0, 1.5, -2
					    def c12, -3, 0.5, 0, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c11.xxxy, c11.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov r0.yz, c11
					    slt r0.x, c10.x, r0.y
					    mad r0.yw, v2.xxzy, c8.xxzy, c8.xzzw
					    mad r1.x, r0.w, c11.w, c11.x
					    mad o2.yw, r0.x, r1.x, r0.w
					    mov o1, v1
					    mul r0.x, r0.z, c9.x
					    mov r1.xy, c12
					    mad r0.z, c9.x, r1.x, r1.y
					    mad r0.x, r0.y, r0.z, r0.x
					    add o2.z, r0.x, c12.y
					    mov o2.x, r0.x
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 23 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mad r0.yz, v2.xxyx, cb0[2].xxyx, cb0[2].zzwz
					add r0.w, -r0.z, l(1.000000)
					movc o2.yw, r0.xxxx, r0.wwww, r0.zzzz
					mul r0.x, cb0[3].x, l(1.500000)
					mad r0.z, cb0[3].x, l(-3.000000), l(0.500000)
					mad r0.x, r0.y, r0.z, r0.x
					add o2.z, r0.x, l(0.500000)
					mov o2.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _MainTex_TexelSize  c9       1
					//   _VertScale          c10      1
					//
					
					    vs_3_0
					    def c11, 1, 0, 1.5, -2
					    def c12, -3, 0.5, 0, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c11.xxxy, c11.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov r0.yz, c11
					    slt r0.x, c10.x, r0.y
					    mad r0.yw, v2.xxzy, c8.xxzy, c8.xzzw
					    mad r1.x, r0.w, c11.w, c11.x
					    mad o2.yw, r0.x, r1.x, r0.w
					    mov o1, v1
					    mul r0.x, r0.z, c9.x
					    mov r1.xy, c12
					    mad r0.z, c9.x, r1.x, r1.y
					    mad r0.x, r0.y, r0.z, r0.x
					    add o2.z, r0.x, c12.y
					    mov o2.x, r0.x
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 23 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mad r0.yz, v2.xxyx, cb0[2].xxyx, cb0[2].zzwz
					add r0.w, -r0.z, l(1.000000)
					movc o2.yw, r0.xxxx, r0.wwww, r0.zzzz
					mul r0.x, cb0[3].x, l(1.500000)
					mad r0.z, cb0[3].x, l(-3.000000), l(0.500000)
					mad r0.x, r0.y, r0.z, r0.x
					add o2.z, r0.x, l(0.500000)
					mov o2.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _MainTex_TexelSize  c9       1
					//   _VertScale          c10      1
					//
					
					    vs_3_0
					    def c11, 1, 0, 1.5, -2
					    def c12, -3, 0.5, 0, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c11.xxxy, c11.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov r0.yz, c11
					    slt r0.x, c10.x, r0.y
					    mad r0.yw, v2.xxzy, c8.xxzy, c8.xzzw
					    mad r1.x, r0.w, c11.w, c11.x
					    mad o2.yw, r0.x, r1.x, r0.w
					    mov o1, v1
					    mul r0.x, r0.z, c9.x
					    mov r1.xy, c12
					    mad r0.z, c9.x, r1.x, r1.y
					    mad r0.x, r0.y, r0.z, r0.x
					    add o2.z, r0.x, c12.y
					    mov o2.x, r0.x
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 23 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mad r0.yz, v2.xxyx, cb0[2].xxyx, cb0[2].zzwz
					add r0.w, -r0.z, l(1.000000)
					movc o2.yw, r0.xxxx, r0.wwww, r0.zzzz
					mul r0.x, cb0[3].x, l(1.500000)
					mad r0.z, cb0[3].x, l(-3.000000), l(0.500000)
					mad r0.x, r0.y, r0.z, r0.x
					add o2.z, r0.x, l(0.500000)
					mov o2.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float _VertScale;
					//   row_major float4x4 unity_MatrixVP;
					//   row_major float4x4 unity_ObjectToWorld;
					//
					//
					// Registers:
					//
					//   Name                Reg   Size
					//   ------------------- ----- ----
					//   unity_ObjectToWorld c0       4
					//   unity_MatrixVP      c4       4
					//   _MainTex_ST         c8       1
					//   _MainTex_TexelSize  c9       1
					//   _VertScale          c10      1
					//
					
					    vs_3_0
					    def c11, 1, 0, 1.5, -2
					    def c12, -3, 0.5, 0, 0
					    dcl_position v0
					    dcl_color v1
					    dcl_texcoord v2
					    dcl_position o0
					    dcl_color o1
					    dcl_texcoord o2
					    mad r0, v0.xyzx, c11.xxxy, c11.yyyx
					    dp4 r1.x, c0, r0
					    dp4 r1.y, c1, r0
					    dp4 r1.z, c2, r0
					    dp4 r1.w, c3, r0
					    dp4 r2.x, c4, r1
					    dp4 r2.y, c5, r1
					    dp4 r2.z, c6, r1
					    dp4 r2.w, c7, r1
					    mov r0.yz, c11
					    slt r0.x, c10.x, r0.y
					    mad r0.yw, v2.xxzy, c8.xxzy, c8.xzzw
					    mad r1.x, r0.w, c11.w, c11.x
					    mad o2.yw, r0.x, r1.x, r0.w
					    mov o1, v1
					    mul r0.x, r0.z, c9.x
					    mov r1.xy, c12
					    mad r0.z, c9.x, r1.x, r1.y
					    mad r0.x, r0.y, r0.z, r0.x
					    add o2.z, r0.x, c12.y
					    mov o2.x, r0.x
					    mad o0.xy, r2.w, c255, r2
					    mov o0.zw, r2
					
					// approximately 23 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb1[3].xyzw
					mul r1.xyzw, r0.yyyy, cb2[18].xyzw
					mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
					mov o1.xyzw, v1.xyzw
					lt r0.x, cb0[4].x, l(0.000000)
					mad r0.yz, v2.xxyx, cb0[2].xxyx, cb0[2].zzwz
					add r0.w, -r0.z, l(1.000000)
					movc o2.yw, r0.xxxx, r0.wwww, r0.zzzz
					mul r0.x, cb0[3].x, l(1.500000)
					mad r0.z, cb0[3].x, l(-3.000000), l(0.500000)
					mad r0.x, r0.y, r0.z, r0.x
					add o2.z, r0.x, l(0.500000)
					mov o2.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    dcl_color_pp v0
					    dcl_texcoord v1.xy
					    dcl_2d s0
					    texld_pp r0, v1, s0
					    mul_pp oC0, r0, v0
					
					// approximately 2 instruction slots used (1 texture, 1 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c0, 0, -0.5, 1, 1.40199995
					    def c1, 1, -0.344139993, -0.714139998, 0
					    def c2, 1, 1.77199996, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1.xy
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v1, s0
					    texld r1, v1, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c0.xyyw
					    dp2add_pp r1.x, c0.zwzw, r0.xzzw, c0.x
					    dp3_pp r1.y, c1, r0
					    dp2add_pp r1.z, c2, r0, c2.z
					    mov r1.w, c0.z
					    mul_pp oC0, r1, v0
					
					// approximately 11 instruction slots used (2 texture, 9 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					sample r1.xyzw, v2.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r1.x, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					dp3 r1.y, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r1.z, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					mov r1.w, l(1.000000)
					mul o0.xyzw, r1.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c0, 0.416666657, 1.05499995, -0.0549999997, 0
					    dcl_color_pp v0
					    dcl_texcoord v1.xy
					    dcl_2d s0
					    texld_pp r0, v1, s0
					    log_pp r1.x, r0.x
					    log_pp r1.y, r0.y
					    log_pp r1.z, r0.z
					    mul_pp r1.xyz, r1, c0.x
					    exp_pp r2.x, r1.x
					    exp_pp r2.y, r1.y
					    exp_pp r2.z, r1.z
					    mad_pp r1.xyz, r2, c0.y, c0.z
					    max_pp r0.xyz, r1, c0.w
					    mul_pp oC0, r0, v0
					
					// approximately 11 instruction slots used (1 texture, 10 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					log r1.xyz, r0.xyzx
					mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r1.xyz, r1.xyzx
					mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c0, 0, -0.5, 1, 1.40199995
					    def c1, 1.05499995, -0.0549999997, 0, 0
					    def c2, 1, -0.344139993, -0.714139998, 0.416666657
					    def c3, 1, 1.77199996, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1.xy
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v1, s0
					    texld r1, v1, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c0.xyyw
					    dp2add_pp r0.w, c0.zwzw, r0.xzzw, c0.x
					    log_pp r1.x, r0.w
					    dp3_pp r0.z, c2, r0
					    dp2add_pp r0.x, c3, r0, c3.z
					    log_pp r1.z, r0.x
					    log_pp r1.y, r0.z
					    mul_pp r0.xyz, r1, c2.w
					    exp_pp r1.x, r0.x
					    exp_pp r1.y, r0.y
					    exp_pp r1.z, r0.z
					    mad_pp r0.xyz, r1, c1.x, c1.y
					    max_pp r1.xyz, r0, c0.x
					    mov r1.w, c0.z
					    mul_pp oC0, r1, v0
					
					// approximately 20 instruction slots used (2 texture, 18 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					sample r1.xyzw, v2.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r0.w, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					log r1.x, r0.w
					dp3 r0.z, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r0.x, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					log r1.z, r0.x
					log r1.y, r0.z
					mul r0.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r0.xyz, r0.xyzx
					mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					mov r0.w, l(1.000000)
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c0, 0.333333343, 0, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1
					    dcl_2d s0
					    texld_pp r0, v1.zwzw, s0
					    add_pp r0.x, r0.y, r0.x
					    add_pp r0.x, r0.z, r0.x
					    mul_pp r0.w, r0.x, c0.x
					    texld_pp r1, v1, s0
					    mov_pp r0.xyz, r1
					    mul_pp oC0, r0, v0
					
					// approximately 7 instruction slots used (2 texture, 5 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.zwzz, t0.xyzw, s0
					add r0.x, r0.y, r0.x
					add r0.x, r0.z, r0.x
					mul r0.w, r0.x, l(0.333333)
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					mov r0.xyz, r1.xyzx
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c0, 0, -0.5, 1, 1.40199995
					    def c1, 1, -0.344139993, -0.714139998, 0
					    def c2, 1, 1.77199996, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1
					    dcl_2d s0
					    dcl_2d s1
					    texld_pp r0, v1.zwzw, s0
					    mov_pp r0.w, r0.x
					    texld r1, v1, s0
					    texld r2, v1, s1
					    mov r1.yz, r2.xxww
					    add r1.xyz, r1, c0.xyyw
					    dp2add_pp r0.x, c0.zwzw, r1.xzzw, c0.x
					    dp3_pp r0.y, c1, r1
					    dp2add_pp r0.z, c2, r1, c2.z
					    mul_pp oC0, r0, v0
					
					// approximately 12 instruction slots used (3 texture, 9 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v2.zwzz, t0.yzwx, s0
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					sample r2.xyzw, v2.xyxx, t1.xyzw, s1
					mov r1.yz, r2.xxwx
					add r1.xyz, r1.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r0.x, l(1.000000, 1.402000, 0.000000, 0.000000), r1.xzxx
					dp3 r0.y, l(1.000000, -0.344140, -0.714140, 0.000000), r1.xyzx
					dp2 r0.z, l(1.000000, 1.772000, 0.000000, 0.000000), r1.xyxx
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c0, 0.416666657, 1.05499995, -0.0549999997, 0
					    def c1, 0.333333343, 0, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1
					    dcl_2d s0
					    texld_pp r0, v1.zwzw, s0
					    log_pp r1.x, r0.x
					    log_pp r1.y, r0.y
					    log_pp r1.z, r0.z
					    mul_pp r0.xyz, r1, c0.x
					    exp_pp r1.x, r0.x
					    exp_pp r1.y, r0.y
					    exp_pp r1.z, r0.z
					    mad_pp r0.xyz, r1, c0.y, c0.z
					    max_pp r1.xyz, r0, c0.w
					    add_pp r0.x, r1.y, r1.x
					    add_pp r0.x, r1.z, r0.x
					    mul_pp r0.w, r0.x, c1.x
					    texld_pp r1, v1, s0
					    log_pp r2.x, r1.x
					    log_pp r2.y, r1.y
					    log_pp r2.z, r1.z
					    mul_pp r1.xyz, r2, c0.x
					    exp_pp r2.x, r1.x
					    exp_pp r2.y, r1.y
					    exp_pp r2.z, r1.z
					    mad_pp r1.xyz, r2, c0.y, c0.z
					    max_pp r0.xyz, r1, c0.w
					    mul_pp oC0, r0, v0
					
					// approximately 24 instruction slots used (2 texture, 22 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.zwzz, t0.xyzw, s0
					log r0.xyz, r0.xyzx
					mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r0.xyz, r0.xyzx
					mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					add r0.x, r0.y, r0.x
					add r0.x, r0.z, r0.x
					mul r0.w, r0.x, l(0.333333)
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					log r1.xyz, r1.xyzx
					mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r1.xyz, r1.xyzx
					mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c0, 0, -0.5, 1, 1.40199995
					    def c1, 1.05499995, -0.0549999997, 0, 0
					    def c2, 1, -0.344139993, -0.714139998, 0.416666657
					    def c3, 1, 1.77199996, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v1, s0
					    texld r1, v1, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c0.xyyw
					    dp2add_pp r0.w, c0.zwzw, r0.xzzw, c0.x
					    log_pp r1.x, r0.w
					    dp3_pp r0.z, c2, r0
					    dp2add_pp r0.x, c3, r0, c3.z
					    log_pp r1.z, r0.x
					    log_pp r1.y, r0.z
					    mul_pp r0.xyz, r1, c2.w
					    exp_pp r1.x, r0.x
					    exp_pp r1.y, r0.y
					    exp_pp r1.z, r0.z
					    mad_pp r0.xyz, r1, c1.x, c1.y
					    max_pp r1.xyz, r0, c0.x
					    texld_pp r0, v1.zwzw, s0
					    mov_pp r1.w, r0.x
					    mul_pp oC0, r1, v0
					
					// approximately 21 instruction slots used (3 texture, 18 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					sample r1.xyzw, v2.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r0.w, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					log r1.x, r0.w
					dp3 r0.z, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r0.x, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					log r1.z, r0.x
					log r1.y, r0.z
					mul r0.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r0.xyz, r0.xyzx
					mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					sample r1.xyzw, v2.zwzz, t0.xyzw, s0
					mov r0.w, r1.x
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c0, 0.333333343, 0, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1
					    dcl_2d s0
					    texld_pp r0, v1.zwzw, s0
					    add_pp r0.x, r0.y, r0.x
					    add_pp r0.x, r0.z, r0.x
					    mul_pp r0.w, r0.x, c0.x
					    texld_pp r1, v1, s0
					    mov_pp r0.xyz, r1
					    mul_pp oC0, r0, v0
					
					// approximately 7 instruction slots used (2 texture, 5 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.zwzz, t0.xyzw, s0
					add r0.x, r0.y, r0.x
					add r0.x, r0.z, r0.x
					mul r0.w, r0.x, l(0.333333)
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					mov r0.xyz, r1.xyzx
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c0, 0, -0.5, 1, 1.40199995
					    def c1, 1, -0.344139993, -0.714139998, 0
					    def c2, 1, 1.77199996, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1
					    dcl_2d s0
					    dcl_2d s1
					    texld_pp r0, v1.zwzw, s0
					    mov_pp r0.w, r0.x
					    texld r1, v1, s0
					    texld r2, v1, s1
					    mov r1.yz, r2.xxww
					    add r1.xyz, r1, c0.xyyw
					    dp2add_pp r0.x, c0.zwzw, r1.xzzw, c0.x
					    dp3_pp r0.y, c1, r1
					    dp2add_pp r0.z, c2, r1, c2.z
					    mul_pp oC0, r0, v0
					
					// approximately 12 instruction slots used (3 texture, 9 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v2.zwzz, t0.yzwx, s0
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					sample r2.xyzw, v2.xyxx, t1.xyzw, s1
					mov r1.yz, r2.xxwx
					add r1.xyz, r1.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r0.x, l(1.000000, 1.402000, 0.000000, 0.000000), r1.xzxx
					dp3 r0.y, l(1.000000, -0.344140, -0.714140, 0.000000), r1.xyzx
					dp2 r0.z, l(1.000000, 1.772000, 0.000000, 0.000000), r1.xyxx
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c0, 0.416666657, 1.05499995, -0.0549999997, 0
					    def c1, 0.333333343, 0, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1
					    dcl_2d s0
					    texld_pp r0, v1.zwzw, s0
					    log_pp r1.x, r0.x
					    log_pp r1.y, r0.y
					    log_pp r1.z, r0.z
					    mul_pp r0.xyz, r1, c0.x
					    exp_pp r1.x, r0.x
					    exp_pp r1.y, r0.y
					    exp_pp r1.z, r0.z
					    mad_pp r0.xyz, r1, c0.y, c0.z
					    max_pp r1.xyz, r0, c0.w
					    add_pp r0.x, r1.y, r1.x
					    add_pp r0.x, r1.z, r0.x
					    mul_pp r0.w, r0.x, c1.x
					    texld_pp r1, v1, s0
					    log_pp r2.x, r1.x
					    log_pp r2.y, r1.y
					    log_pp r2.z, r1.z
					    mul_pp r1.xyz, r2, c0.x
					    exp_pp r2.x, r1.x
					    exp_pp r2.y, r1.y
					    exp_pp r2.z, r1.z
					    mad_pp r1.xyz, r2, c0.y, c0.z
					    max_pp r0.xyz, r1, c0.w
					    mul_pp oC0, r0, v0
					
					// approximately 24 instruction slots used (2 texture, 22 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.zwzz, t0.xyzw, s0
					log r0.xyz, r0.xyzx
					mul r0.xyz, r0.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r0.xyz, r0.xyzx
					mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					add r0.x, r0.y, r0.x
					add r0.x, r0.z, r0.x
					mul r0.w, r0.x, l(0.333333)
					sample r1.xyzw, v2.xyxx, t0.xyzw, s0
					log r1.xyz, r1.xyzx
					mul r1.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r1.xyz, r1.xyzx
					mad r1.xyz, r1.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c0, 0, -0.5, 1, 1.40199995
					    def c1, 1.05499995, -0.0549999997, 0, 0
					    def c2, 1, -0.344139993, -0.714139998, 0.416666657
					    def c3, 1, 1.77199996, 0, 0
					    dcl_color_pp v0
					    dcl_texcoord v1
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v1, s0
					    texld r1, v1, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c0.xyyw
					    dp2add_pp r0.w, c0.zwzw, r0.xzzw, c0.x
					    log_pp r1.x, r0.w
					    dp3_pp r0.z, c2, r0
					    dp2add_pp r0.x, c3, r0, c3.z
					    log_pp r1.z, r0.x
					    log_pp r1.y, r0.z
					    mul_pp r0.xyz, r1, c2.w
					    exp_pp r1.x, r0.x
					    exp_pp r1.y, r0.y
					    exp_pp r1.z, r0.z
					    mad_pp r0.xyz, r1, c1.x, c1.y
					    max_pp r1.xyz, r0, c0.x
					    texld_pp r0, v1.zwzw, s0
					    mov_pp r1.w, r0.x
					    mul_pp oC0, r1, v0
					
					// approximately 21 instruction slots used (3 texture, 18 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					sample r1.xyzw, v2.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r0.w, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					log r1.x, r0.w
					dp3 r0.z, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r0.x, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					log r1.z, r0.x
					log r1.y, r0.z
					mul r0.xyz, r1.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
					exp r0.xyz, r0.xyzx
					mad r0.xyz, r0.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
					max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
					sample r1.xyzw, v2.zwzz, t0.xyzw, s0
					mov r0.w, r1.x
					mul o0.xyzw, r0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}