Shader "AVProVideo/Background/Full Screen Transparent" {
	Properties {
		_MainTex ("Texture", 2D) = "black" {}
		_ChromaTex ("Chroma", 2D) = "gray" {}
		_Color ("Main Color", Vector) = (1,1,1,1)
		[KeywordEnum(None, Top_Bottom, Left_Right)] AlphaPack ("Alpha Pack", Float) = 0
		[Toggle(APPLY_GAMMA)] _ApplyGamma ("Apply Gamma", Float) = 0
		[Toggle(USE_YPCBCR)] _UseYpCbCr ("Use YpCbCr", Float) = 0
	}
	SubShader {
		LOD 100
		Tags { "QUEUE" = "Background+1" "RenderType" = "Transparent" }
		Pass {
			LOD 100
			Tags { "QUEUE" = "Background+1" "RenderType" = "Transparent" }
			Blend SrcAlpha OneMinusSrcAlpha, SrcAlpha OneMinusSrcAlpha
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 54440
			Program "vp" {
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 1, 0, -4, -2
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.x
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    mov r1.y, c4.y
					    slt r0.z, c0.x, r1.y
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c4.z, r0.y
					    mad r3.xzw, r0.x, c4.xyyy, c4.yyyx
					    slt r0.x, c2.y, r1.y
					    mad r1.xy, v1, c2, c2.zwzw
					    mad r0.y, r1.y, c4.w, c4.x
					    mad r0.y, r0.x, r0.y, r1.y
					    mad r0.z, r0.y, c4.w, c4.x
					    mad r1.z, r0.x, r0.z, r0.y
					    mov o1, r1.xzxz
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 27 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					div r1.x, cb1[6].y, cb1[6].x
					div r1.y, cb0[3].w, cb0[3].z
					lt r1.z, r1.x, r1.y
					div r0.xw, r1.xxxy, r1.yyyx
					movc r0.xy, r1.zzzz, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					lt r0.x, cb0[2].y, l(0.000000)
					mad r1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.y, -r1.y, l(1.000000)
					movc r0.y, r0.x, r0.y, r1.y
					add r0.y, -r0.y, l(1.000000)
					movc r1.z, r0.x, r0.y, r1.y
					mov o1.xyzw, r1.xzxz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 1, 0, -4, -2
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.x
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    mov r1.y, c4.y
					    slt r0.z, c0.x, r1.y
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c4.z, r0.y
					    mad r3.xzw, r0.x, c4.xyyy, c4.yyyx
					    slt r0.x, c2.y, r1.y
					    mad r1.xy, v1, c2, c2.zwzw
					    mad r0.y, r1.y, c4.w, c4.x
					    mad r0.y, r0.x, r0.y, r1.y
					    mad r0.z, r0.y, c4.w, c4.x
					    mad r1.z, r0.x, r0.z, r0.y
					    mov o1, r1.xzxz
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 27 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					div r1.x, cb1[6].y, cb1[6].x
					div r1.y, cb0[3].w, cb0[3].z
					lt r1.z, r1.x, r1.y
					div r0.xw, r1.xxxy, r1.yyyx
					movc r0.xy, r1.zzzz, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					lt r0.x, cb0[2].y, l(0.000000)
					mad r1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.y, -r1.y, l(1.000000)
					movc r0.y, r0.x, r0.y, r1.y
					add r0.y, -r0.y, l(1.000000)
					movc r1.z, r0.x, r0.y, r1.y
					mov o1.xyzw, r1.xzxz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 1, 0, -4, -2
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.x
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    mov r1.y, c4.y
					    slt r0.z, c0.x, r1.y
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c4.z, r0.y
					    mad r3.xzw, r0.x, c4.xyyy, c4.yyyx
					    slt r0.x, c2.y, r1.y
					    mad r1.xy, v1, c2, c2.zwzw
					    mad r0.y, r1.y, c4.w, c4.x
					    mad r0.y, r0.x, r0.y, r1.y
					    mad r0.z, r0.y, c4.w, c4.x
					    mad r1.z, r0.x, r0.z, r0.y
					    mov o1, r1.xzxz
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 27 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					div r1.x, cb1[6].y, cb1[6].x
					div r1.y, cb0[3].w, cb0[3].z
					lt r1.z, r1.x, r1.y
					div r0.xw, r1.xxxy, r1.yyyx
					movc r0.xy, r1.zzzz, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					lt r0.x, cb0[2].y, l(0.000000)
					mad r1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.y, -r1.y, l(1.000000)
					movc r0.y, r0.x, r0.y, r1.y
					add r0.y, -r0.y, l(1.000000)
					movc r1.z, r0.x, r0.y, r1.y
					mov o1.xyzw, r1.xzxz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 1, 0, -4, -2
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.x
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    mov r1.y, c4.y
					    slt r0.z, c0.x, r1.y
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c4.z, r0.y
					    mad r3.xzw, r0.x, c4.xyyy, c4.yyyx
					    slt r0.x, c2.y, r1.y
					    mad r1.xy, v1, c2, c2.zwzw
					    mad r0.y, r1.y, c4.w, c4.x
					    mad r0.y, r0.x, r0.y, r1.y
					    mad r0.z, r0.y, c4.w, c4.x
					    mad r1.z, r0.x, r0.z, r0.y
					    mov o1, r1.xzxz
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 27 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					div r1.x, cb1[6].y, cb1[6].x
					div r1.y, cb0[3].w, cb0[3].z
					lt r1.z, r1.x, r1.y
					div r0.xw, r1.xxxy, r1.yyyx
					movc r0.xy, r1.zzzz, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					lt r0.x, cb0[2].y, l(0.000000)
					mad r1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.y, -r1.y, l(1.000000)
					movc r0.y, r0.x, r0.y, r1.y
					add r0.y, -r0.y, l(1.000000)
					movc r1.z, r0.x, r0.y, r1.y
					mov o1.xyzw, r1.xzxz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 0.5, 1.5, 1, 0
					    def c5, -3, 0.5, 0, 0
					    def c6, -4, -2, 1, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.z
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mov r2.xyw, c4
					    mul r2.xy, r2, c3.wyzw
					    mul r1.z, r1.z, r2.x
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xz, r1.z, r0.zyww, r0.xyyw
					    mul r0.xy, r2.xzzw, v0
					    slt r0.z, c0.x, r2.w
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c6.x, r0.y
					    mad r3.xzw, r0.x, c4.zyww, c4.wywz
					    mov r0.y, c3.y
					    mad r0.x, r0.y, c5.x, c5.y
					    slt r0.y, c2.y, r2.w
					    mad r1.xy, v1, c2, c2.zwzw
					    mad r0.z, r1.y, c6.y, c6.z
					    mad r0.z, r0.y, r0.z, r1.y
					    mad r0.z, r0.z, r0.x, r2.y
					    add r0.w, r0.z, c4.x
					    add r0.x, -r0.z, -r0.w
					    add r0.x, r0.x, c4.z
					    mad r1.zw, r0.y, r0.x, r0
					    mov o1, r1.xzxw
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 33 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 3
					mov r0.yz, l(0,1.000000,1.000000,0)
					mul r1.xy, cb0[3].wyww, l(0.500000, 1.500000, 0.000000, 0.000000)
					div r1.x, r1.x, cb0[3].z
					div r1.z, cb1[6].y, cb1[6].x
					lt r1.w, r1.z, r1.x
					div r0.xw, r1.zzzx, r1.xxxz
					movc r0.xy, r1.wwww, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					mad r0.x, cb0[3].y, l(-3.000000), l(0.500000)
					lt r0.y, cb0[2].y, l(0.000000)
					mad r2.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.z, -r2.y, l(1.000000)
					movc r0.z, r0.y, r0.z, r2.y
					mad r0.z, r0.z, r0.x, r1.y
					add r0.w, r0.z, l(0.500000)
					add r1.xy, -r0.wzww, l(1.000000, 1.000000, 0.000000, 0.000000)
					movc r2.zw, r0.yyyy, r1.xxxy, r0.zzzw
					mov o1.xyzw, r2.xzxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 0.5, 1.5, 1, 0
					    def c5, -3, 0.5, 0, 0
					    def c6, -4, -2, 1, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.z
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mov r2.xyw, c4
					    mul r2.xy, r2, c3.wyzw
					    mul r1.z, r1.z, r2.x
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xz, r1.z, r0.zyww, r0.xyyw
					    mul r0.xy, r2.xzzw, v0
					    slt r0.z, c0.x, r2.w
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c6.x, r0.y
					    mad r3.xzw, r0.x, c4.zyww, c4.wywz
					    mov r0.y, c3.y
					    mad r0.x, r0.y, c5.x, c5.y
					    slt r0.y, c2.y, r2.w
					    mad r1.xy, v1, c2, c2.zwzw
					    mad r0.z, r1.y, c6.y, c6.z
					    mad r0.z, r0.y, r0.z, r1.y
					    mad r0.z, r0.z, r0.x, r2.y
					    add r0.w, r0.z, c4.x
					    add r0.x, -r0.z, -r0.w
					    add r0.x, r0.x, c4.z
					    mad r1.zw, r0.y, r0.x, r0
					    mov o1, r1.xzxw
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 33 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 3
					mov r0.yz, l(0,1.000000,1.000000,0)
					mul r1.xy, cb0[3].wyww, l(0.500000, 1.500000, 0.000000, 0.000000)
					div r1.x, r1.x, cb0[3].z
					div r1.z, cb1[6].y, cb1[6].x
					lt r1.w, r1.z, r1.x
					div r0.xw, r1.zzzx, r1.xxxz
					movc r0.xy, r1.wwww, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					mad r0.x, cb0[3].y, l(-3.000000), l(0.500000)
					lt r0.y, cb0[2].y, l(0.000000)
					mad r2.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.z, -r2.y, l(1.000000)
					movc r0.z, r0.y, r0.z, r2.y
					mad r0.z, r0.z, r0.x, r1.y
					add r0.w, r0.z, l(0.500000)
					add r1.xy, -r0.wzww, l(1.000000, 1.000000, 0.000000, 0.000000)
					movc r2.zw, r0.yyyy, r1.xxxy, r0.zzzw
					mov o1.xyzw, r2.xzxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 0.5, 1.5, 1, 0
					    def c5, -3, 0.5, 0, 0
					    def c6, -4, -2, 1, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.z
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mov r2.xyw, c4
					    mul r2.xy, r2, c3.wyzw
					    mul r1.z, r1.z, r2.x
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xz, r1.z, r0.zyww, r0.xyyw
					    mul r0.xy, r2.xzzw, v0
					    slt r0.z, c0.x, r2.w
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c6.x, r0.y
					    mad r3.xzw, r0.x, c4.zyww, c4.wywz
					    mov r0.y, c3.y
					    mad r0.x, r0.y, c5.x, c5.y
					    slt r0.y, c2.y, r2.w
					    mad r1.xy, v1, c2, c2.zwzw
					    mad r0.z, r1.y, c6.y, c6.z
					    mad r0.z, r0.y, r0.z, r1.y
					    mad r0.z, r0.z, r0.x, r2.y
					    add r0.w, r0.z, c4.x
					    add r0.x, -r0.z, -r0.w
					    add r0.x, r0.x, c4.z
					    mad r1.zw, r0.y, r0.x, r0
					    mov o1, r1.xzxw
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 33 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 3
					mov r0.yz, l(0,1.000000,1.000000,0)
					mul r1.xy, cb0[3].wyww, l(0.500000, 1.500000, 0.000000, 0.000000)
					div r1.x, r1.x, cb0[3].z
					div r1.z, cb1[6].y, cb1[6].x
					lt r1.w, r1.z, r1.x
					div r0.xw, r1.zzzx, r1.xxxz
					movc r0.xy, r1.wwww, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					mad r0.x, cb0[3].y, l(-3.000000), l(0.500000)
					lt r0.y, cb0[2].y, l(0.000000)
					mad r2.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.z, -r2.y, l(1.000000)
					movc r0.z, r0.y, r0.z, r2.y
					mad r0.z, r0.z, r0.x, r1.y
					add r0.w, r0.z, l(0.500000)
					add r1.xy, -r0.wzww, l(1.000000, 1.000000, 0.000000, 0.000000)
					movc r2.zw, r0.yyyy, r1.xxxy, r0.zzzw
					mov o1.xyzw, r2.xzxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 0.5, 1.5, 1, 0
					    def c5, -3, 0.5, 0, 0
					    def c6, -4, -2, 1, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.z
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mov r2.xyw, c4
					    mul r2.xy, r2, c3.wyzw
					    mul r1.z, r1.z, r2.x
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xz, r1.z, r0.zyww, r0.xyyw
					    mul r0.xy, r2.xzzw, v0
					    slt r0.z, c0.x, r2.w
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c6.x, r0.y
					    mad r3.xzw, r0.x, c4.zyww, c4.wywz
					    mov r0.y, c3.y
					    mad r0.x, r0.y, c5.x, c5.y
					    slt r0.y, c2.y, r2.w
					    mad r1.xy, v1, c2, c2.zwzw
					    mad r0.z, r1.y, c6.y, c6.z
					    mad r0.z, r0.y, r0.z, r1.y
					    mad r0.z, r0.z, r0.x, r2.y
					    add r0.w, r0.z, c4.x
					    add r0.x, -r0.z, -r0.w
					    add r0.x, r0.x, c4.z
					    mad r1.zw, r0.y, r0.x, r0
					    mov o1, r1.xzxw
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 33 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 3
					mov r0.yz, l(0,1.000000,1.000000,0)
					mul r1.xy, cb0[3].wyww, l(0.500000, 1.500000, 0.000000, 0.000000)
					div r1.x, r1.x, cb0[3].z
					div r1.z, cb1[6].y, cb1[6].x
					lt r1.w, r1.z, r1.x
					div r0.xw, r1.zzzx, r1.xxxz
					movc r0.xy, r1.wwww, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					mad r0.x, cb0[3].y, l(-3.000000), l(0.500000)
					lt r0.y, cb0[2].y, l(0.000000)
					mad r2.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					add r0.z, -r2.y, l(1.000000)
					movc r0.z, r0.y, r0.z, r2.y
					mad r0.z, r0.z, r0.x, r1.y
					add r0.w, r0.z, l(0.500000)
					add r1.xy, -r0.wzww, l(1.000000, 1.000000, 0.000000, 0.000000)
					movc r2.zw, r0.yyyy, r1.xxxy, r0.zzzw
					mov o1.xyzw, r2.xzxw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 0.5, 1.5, 1, 0
					    def c5, -3, 0.5, 0, 0
					    def c6, -4, -2, 1, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.z
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    mov r2.xyw, c4
					    mul r1.zw, r2.xyxy, c3.xyzx
					    rcp r1.z, r1.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    slt r0.z, c0.x, r2.w
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c6.x, r0.y
					    mad r3.xzw, r0.x, c4.zyww, c4.wywz
					    slt r0.x, c2.y, r2.w
					    mad r0.yz, v1.xxyw, c2.xxyw, c2.xzww
					    mad r0.w, r0.z, c6.y, c6.z
					    mad r0.z, r0.x, r0.w, r0.z
					    mad r0.w, r0.z, c6.y, c6.z
					    mad o1.yw, r0.x, r0.w, r0.z
					    mov r0.x, c3.x
					    mad r0.x, r0.x, c5.x, c5.y
					    mad r0.x, r0.y, r0.x, r1.w
					    add o1.z, r0.x, c4.x
					    mov o1.x, r0.x
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 32 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					mul r1.xy, cb0[3].zxzz, l(0.500000, 1.500000, 0.000000, 0.000000)
					div r1.x, cb0[3].w, r1.x
					div r1.z, cb1[6].y, cb1[6].x
					lt r1.w, r1.z, r1.x
					div r0.xw, r1.zzzx, r1.xxxz
					movc r0.xy, r1.wwww, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					lt r0.x, cb0[2].y, l(0.000000)
					mad r0.yz, v1.xxyx, cb0[2].xxyx, cb0[2].zzwz
					add r0.w, -r0.z, l(1.000000)
					movc r0.w, r0.x, r0.w, r0.z
					add r0.w, -r0.w, l(1.000000)
					movc o1.yw, r0.xxxx, r0.wwww, r0.zzzz
					mad r0.x, cb0[3].x, l(-3.000000), l(0.500000)
					mad r0.x, r0.y, r0.x, r1.y
					add o1.z, r0.x, l(0.500000)
					mov o1.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 0.5, 1.5, 1, 0
					    def c5, -3, 0.5, 0, 0
					    def c6, -4, -2, 1, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.z
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    mov r2.xyw, c4
					    mul r1.zw, r2.xyxy, c3.xyzx
					    rcp r1.z, r1.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    slt r0.z, c0.x, r2.w
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c6.x, r0.y
					    mad r3.xzw, r0.x, c4.zyww, c4.wywz
					    slt r0.x, c2.y, r2.w
					    mad r0.yz, v1.xxyw, c2.xxyw, c2.xzww
					    mad r0.w, r0.z, c6.y, c6.z
					    mad r0.z, r0.x, r0.w, r0.z
					    mad r0.w, r0.z, c6.y, c6.z
					    mad o1.yw, r0.x, r0.w, r0.z
					    mov r0.x, c3.x
					    mad r0.x, r0.x, c5.x, c5.y
					    mad r0.x, r0.y, r0.x, r1.w
					    add o1.z, r0.x, c4.x
					    mov o1.x, r0.x
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 32 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					mul r1.xy, cb0[3].zxzz, l(0.500000, 1.500000, 0.000000, 0.000000)
					div r1.x, cb0[3].w, r1.x
					div r1.z, cb1[6].y, cb1[6].x
					lt r1.w, r1.z, r1.x
					div r0.xw, r1.zzzx, r1.xxxz
					movc r0.xy, r1.wwww, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					lt r0.x, cb0[2].y, l(0.000000)
					mad r0.yz, v1.xxyx, cb0[2].xxyx, cb0[2].zzwz
					add r0.w, -r0.z, l(1.000000)
					movc r0.w, r0.x, r0.w, r0.z
					add r0.w, -r0.w, l(1.000000)
					movc o1.yw, r0.xxxx, r0.wwww, r0.zzzz
					mad r0.x, cb0[3].x, l(-3.000000), l(0.500000)
					mad r0.x, r0.y, r0.x, r1.y
					add o1.z, r0.x, l(0.500000)
					mov o1.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 0.5, 1.5, 1, 0
					    def c5, -3, 0.5, 0, 0
					    def c6, -4, -2, 1, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.z
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    mov r2.xyw, c4
					    mul r1.zw, r2.xyxy, c3.xyzx
					    rcp r1.z, r1.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    slt r0.z, c0.x, r2.w
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c6.x, r0.y
					    mad r3.xzw, r0.x, c4.zyww, c4.wywz
					    slt r0.x, c2.y, r2.w
					    mad r0.yz, v1.xxyw, c2.xxyw, c2.xzww
					    mad r0.w, r0.z, c6.y, c6.z
					    mad r0.z, r0.x, r0.w, r0.z
					    mad r0.w, r0.z, c6.y, c6.z
					    mad o1.yw, r0.x, r0.w, r0.z
					    mov r0.x, c3.x
					    mad r0.x, r0.x, c5.x, c5.y
					    mad r0.x, r0.y, r0.x, r1.w
					    add o1.z, r0.x, c4.x
					    mov o1.x, r0.x
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 32 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					mul r1.xy, cb0[3].zxzz, l(0.500000, 1.500000, 0.000000, 0.000000)
					div r1.x, cb0[3].w, r1.x
					div r1.z, cb1[6].y, cb1[6].x
					lt r1.w, r1.z, r1.x
					div r0.xw, r1.zzzx, r1.xxxz
					movc r0.xy, r1.wwww, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					lt r0.x, cb0[2].y, l(0.000000)
					mad r0.yz, v1.xxyx, cb0[2].xxyx, cb0[2].zzwz
					add r0.w, -r0.z, l(1.000000)
					movc r0.w, r0.x, r0.w, r0.z
					add r0.w, -r0.w, l(1.000000)
					movc o1.yw, r0.xxxx, r0.wwww, r0.zzzz
					mad r0.x, cb0[3].x, l(-3.000000), l(0.500000)
					mad r0.x, r0.y, r0.x, r1.y
					add o1.z, r0.x, l(0.500000)
					mov o1.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 0.5, 1.5, 1, 0
					    def c5, -3, 0.5, 0, 0
					    def c6, -4, -2, 1, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1
					    mov r0.xw, c4.z
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    mov r2.xyw, c4
					    mul r1.zw, r2.xyxy, c3.xyzx
					    rcp r1.z, r1.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    slt r0.z, c0.x, r2.w
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c6.x, r0.y
					    mad r3.xzw, r0.x, c4.zyww, c4.wywz
					    slt r0.x, c2.y, r2.w
					    mad r0.yz, v1.xxyw, c2.xxyw, c2.xzww
					    mad r0.w, r0.z, c6.y, c6.z
					    mad r0.z, r0.x, r0.w, r0.z
					    mad r0.w, r0.z, c6.y, c6.z
					    mad o1.yw, r0.x, r0.w, r0.z
					    mov r0.x, c3.x
					    mad r0.x, r0.x, c5.x, c5.y
					    mad r0.x, r0.y, r0.x, r1.w
					    add o1.z, r0.x, c4.x
					    mov o1.x, r0.x
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 32 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					mul r1.xy, cb0[3].zxzz, l(0.500000, 1.500000, 0.000000, 0.000000)
					div r1.x, cb0[3].w, r1.x
					div r1.z, cb1[6].y, cb1[6].x
					lt r1.w, r1.z, r1.x
					div r0.xw, r1.zzzx, r1.xxxz
					movc r0.xy, r1.wwww, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					lt r0.x, cb0[2].y, l(0.000000)
					mad r0.yz, v1.xxyx, cb0[2].xxyx, cb0[2].zzwz
					add r0.w, -r0.z, l(1.000000)
					movc r0.w, r0.x, r0.w, r0.z
					add r0.w, -r0.w, l(1.000000)
					movc o1.yw, r0.xxxx, r0.wwww, r0.zzzz
					mad r0.x, cb0[3].x, l(-3.000000), l(0.500000)
					mad r0.x, r0.y, r0.x, r1.y
					add o1.z, r0.x, l(0.500000)
					mov o1.x, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    texld_pp r0, v0, s0
					    mul_pp oC0, r0, c0
					
					// approximately 2 instruction slots used (1 texture, 1 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c1, 0, -0.5, 1, 1.40199995
					    def c2, 1, -0.344139993, -0.714139998, 0
					    def c3, 1, 1.77199996, 0, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v0, s0
					    texld r1, v0, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c1.xyyw
					    dp2add_pp r1.x, c1.zwzw, r0.xzzw, c1.x
					    dp3_pp r1.y, c2, r0
					    dp2add_pp r1.z, c3, r0, c3.z
					    mov r1.w, c1.z
					    mul_pp oC0, r1, c0
					
					// approximately 11 instruction slots used (2 texture, 9 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					sample r1.xyzw, v1.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r1.x, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					dp3 r1.y, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r1.z, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					mov r1.w, l(1.000000)
					mul o0.xyzw, r1.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 0.305306017, 0.682171106, 0.0125228781, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    texld_pp r0, v0, s0
					    mad_pp r1.xyz, r0, c1.x, c1.y
					    mad_pp r1.xyz, r0, r1, c1.z
					    mul_pp r0.xyz, r0, r1
					    mul_pp oC0, r0, c0
					
					// approximately 5 instruction slots used (1 texture, 4 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					mad r1.xyz, r0.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r1.xyz, r0.xyzx, r1.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xyz, r0.xyzx, r1.xyzx
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c1, 0, -0.5, 1, 1.40199995
					    def c2, 0.305306017, 0.682171106, 0, 0
					    def c3, 1, -0.344139993, -0.714139998, 0.0125228781
					    def c4, 1, 1.77199996, 0, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v0, s0
					    texld r1, v0, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c1.xyyw
					    dp2add_pp r1.x, c1.zwzw, r0.xzzw, c1.x
					    dp3_pp r1.y, c3, r0
					    dp2add_pp r1.z, c4, r0, c4.z
					    mad_pp r0.xyz, r1, c2.x, c2.y
					    mad_pp r0.xyz, r1, r0, c3.w
					    mul_pp r0.xyz, r0, r1
					    mov r0.w, c1.z
					    mul_pp oC0, r0, c0
					
					// approximately 14 instruction slots used (2 texture, 12 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_NONE" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					sample r1.xyzw, v1.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r1.x, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					dp3 r1.y, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r1.z, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					mad r0.xyz, r1.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r0.xyz, r1.xyzx, r0.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xyz, r0.xyzx, r1.xyzx
					mov r0.w, l(1.000000)
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 0.333333343, 0, 0, 0
					    dcl_texcoord v0
					    dcl_2d s0
					    texld_pp r0, v0.zwzw, s0
					    add_pp r0.x, r0.y, r0.x
					    add_pp r0.x, r0.z, r0.x
					    mul_pp r0.w, r0.x, c1.x
					    texld_pp r1, v0, s0
					    mov_pp r0.xyz, r1
					    mul_pp oC0, r0, c0
					
					// approximately 7 instruction slots used (2 texture, 5 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.zwzz, t0.xyzw, s0
					add r0.x, r0.y, r0.x
					add r0.x, r0.z, r0.x
					mul r0.w, r0.x, l(0.333333)
					sample r1.xyzw, v1.xyxx, t0.xyzw, s0
					mov r0.xyz, r1.xyzx
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c1, 0, -0.5, 1, 1.40199995
					    def c2, 1, -0.344139993, -0.714139998, 0
					    def c3, 1, 1.77199996, 0, 0
					    dcl_texcoord v0
					    dcl_2d s0
					    dcl_2d s1
					    texld_pp r0, v0.zwzw, s0
					    mov_pp r0.w, r0.x
					    texld r1, v0, s0
					    texld r2, v0, s1
					    mov r1.yz, r2.xxww
					    add r1.xyz, r1, c1.xyyw
					    dp2add_pp r0.x, c1.zwzw, r1.xzzw, c1.x
					    dp3_pp r0.y, c2, r1
					    dp2add_pp r0.z, c3, r1, c3.z
					    mul_pp oC0, r0, c0
					
					// approximately 12 instruction slots used (3 texture, 9 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v1.zwzz, t0.yzwx, s0
					sample r1.xyzw, v1.xyxx, t0.xyzw, s0
					sample r2.xyzw, v1.xyxx, t1.xyzw, s1
					mov r1.yz, r2.xxwx
					add r1.xyz, r1.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r0.x, l(1.000000, 1.402000, 0.000000, 0.000000), r1.xzxx
					dp3 r0.y, l(1.000000, -0.344140, -0.714140, 0.000000), r1.xyzx
					dp2 r0.z, l(1.000000, 1.772000, 0.000000, 0.000000), r1.xyxx
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 0.305306017, 0.682171106, 0.0125228781, 0.333333343
					    dcl_texcoord v0
					    dcl_2d s0
					    texld_pp r0, v0.zwzw, s0
					    mad_pp r1.xyz, r0, c1.x, c1.y
					    mad_pp r1.xyz, r0, r1, c1.z
					    mul_pp r0.xy, r0, r1
					    add_pp r0.x, r0.y, r0.x
					    mad_pp r0.x, r0.z, r1.z, r0.x
					    mul_pp r0.w, r0.x, c1.w
					    texld_pp r1, v0, s0
					    mad_pp r2.xyz, r1, c1.x, c1.y
					    mad_pp r2.xyz, r1, r2, c1.z
					    mul_pp r0.xyz, r1, r2
					    mul_pp oC0, r0, c0
					
					// approximately 12 instruction slots used (2 texture, 10 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v1.zwzz, t0.xyzw, s0
					mad r1.xyz, r0.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r1.xyz, r0.xyzx, r1.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xy, r0.xyxx, r1.xyxx
					add r0.x, r0.y, r0.x
					mad r0.x, r0.z, r1.z, r0.x
					mul r0.w, r0.x, l(0.333333)
					sample r1.xyzw, v1.xyxx, t0.xyzw, s0
					mad r2.xyz, r1.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r2.xyz, r1.xyzx, r2.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xyz, r1.xyzx, r2.xyzx
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c1, 0, -0.5, 1, 1.40199995
					    def c2, 0.305306017, 0.682171106, 0, 0
					    def c3, 1, -0.344139993, -0.714139998, 0.0125228781
					    def c4, 1, 1.77199996, 0, 0
					    dcl_texcoord v0
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v0, s0
					    texld r1, v0, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c1.xyyw
					    dp2add_pp r1.x, c1.zwzw, r0.xzzw, c1.x
					    dp3_pp r1.y, c3, r0
					    dp2add_pp r1.z, c4, r0, c4.z
					    mad_pp r0.xyz, r1, c2.x, c2.y
					    mad_pp r0.xyz, r1, r0, c3.w
					    mul_pp r0.xyz, r0, r1
					    texld_pp r1, v0.zwzw, s0
					    mov_pp r0.w, r1.x
					    mul_pp oC0, r0, c0
					
					// approximately 15 instruction slots used (3 texture, 12 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_TOP_BOTTOM" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					sample r1.xyzw, v1.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r1.x, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					dp3 r1.y, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r1.z, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					mad r0.xyz, r1.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r0.xyz, r1.xyzx, r0.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xyz, r0.xyzx, r1.xyzx
					sample r1.xyzw, v1.zwzz, t0.xyzw, s0
					mov r0.w, r1.x
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 0.333333343, 0, 0, 0
					    dcl_texcoord v0
					    dcl_2d s0
					    texld_pp r0, v0.zwzw, s0
					    add_pp r0.x, r0.y, r0.x
					    add_pp r0.x, r0.z, r0.x
					    mul_pp r0.w, r0.x, c1.x
					    texld_pp r1, v0, s0
					    mov_pp r0.xyz, r1
					    mul_pp oC0, r0, c0
					
					// approximately 7 instruction slots used (2 texture, 5 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.zwzz, t0.xyzw, s0
					add r0.x, r0.y, r0.x
					add r0.x, r0.z, r0.x
					mul r0.w, r0.x, l(0.333333)
					sample r1.xyzw, v1.xyxx, t0.xyzw, s0
					mov r0.xyz, r1.xyzx
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c1, 0, -0.5, 1, 1.40199995
					    def c2, 1, -0.344139993, -0.714139998, 0
					    def c3, 1, 1.77199996, 0, 0
					    dcl_texcoord v0
					    dcl_2d s0
					    dcl_2d s1
					    texld_pp r0, v0.zwzw, s0
					    mov_pp r0.w, r0.x
					    texld r1, v0, s0
					    texld r2, v0, s1
					    mov r1.yz, r2.xxww
					    add r1.xyz, r1, c1.xyyw
					    dp2add_pp r0.x, c1.zwzw, r1.xzzw, c1.x
					    dp3_pp r0.y, c2, r1
					    dp2add_pp r0.z, c3, r1, c3.z
					    mul_pp oC0, r0, c0
					
					// approximately 12 instruction slots used (3 texture, 9 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v1.zwzz, t0.yzwx, s0
					sample r1.xyzw, v1.xyxx, t0.xyzw, s0
					sample r2.xyzw, v1.xyxx, t1.xyzw, s1
					mov r1.yz, r2.xxwx
					add r1.xyz, r1.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r0.x, l(1.000000, 1.402000, 0.000000, 0.000000), r1.xzxx
					dp3 r0.y, l(1.000000, -0.344140, -0.714140, 0.000000), r1.xyzx
					dp2 r0.z, l(1.000000, 1.772000, 0.000000, 0.000000), r1.xyxx
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 0.305306017, 0.682171106, 0.0125228781, 0.333333343
					    dcl_texcoord v0
					    dcl_2d s0
					    texld_pp r0, v0.zwzw, s0
					    mad_pp r1.xyz, r0, c1.x, c1.y
					    mad_pp r1.xyz, r0, r1, c1.z
					    mul_pp r0.xy, r0, r1
					    add_pp r0.x, r0.y, r0.x
					    mad_pp r0.x, r0.z, r1.z, r0.x
					    mul_pp r0.w, r0.x, c1.w
					    texld_pp r1, v0, s0
					    mad_pp r2.xyz, r1, c1.x, c1.y
					    mad_pp r2.xyz, r1, r2, c1.z
					    mul_pp r0.xyz, r1, r2
					    mul_pp oC0, r0, c0
					
					// approximately 12 instruction slots used (2 texture, 10 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v1.zwzz, t0.xyzw, s0
					mad r1.xyz, r0.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r1.xyz, r0.xyzx, r1.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xy, r0.xyxx, r1.xyxx
					add r0.x, r0.y, r0.x
					mad r0.x, r0.z, r1.z, r0.x
					mul r0.w, r0.x, l(0.333333)
					sample r1.xyzw, v1.xyxx, t0.xyzw, s0
					mad r2.xyz, r1.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r2.xyz, r1.xyzx, r2.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xyz, r1.xyzx, r2.xyzx
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c1, 0, -0.5, 1, 1.40199995
					    def c2, 0.305306017, 0.682171106, 0, 0
					    def c3, 1, -0.344139993, -0.714139998, 0.0125228781
					    def c4, 1, 1.77199996, 0, 0
					    dcl_texcoord v0
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v0, s0
					    texld r1, v0, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c1.xyyw
					    dp2add_pp r1.x, c1.zwzw, r0.xzzw, c1.x
					    dp3_pp r1.y, c3, r0
					    dp2add_pp r1.z, c4, r0, c4.z
					    mad_pp r0.xyz, r1, c2.x, c2.y
					    mad_pp r0.xyz, r1, r0, c3.w
					    mul_pp r0.xyz, r0, r1
					    texld_pp r1, v0.zwzw, s0
					    mov_pp r0.w, r1.x
					    mul_pp oC0, r0, c0
					
					// approximately 15 instruction slots used (3 texture, 12 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "ALPHAPACK_LEFT_RIGHT" "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					sample r1.xyzw, v1.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r1.x, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					dp3 r1.y, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r1.z, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					mad r0.xyz, r1.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r0.xyz, r1.xyzx, r0.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xyz, r0.xyzx, r1.xyzx
					sample r1.xyzw, v1.zwzz, t0.xyzw, s0
					mov r0.w, r1.x
					mul o0.xyzw, r0.xyzw, cb0[4].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}