Shader "AVProVideo/Background/Full Screen" {
	Properties {
		_MainTex ("Texture", 2D) = "black" {}
		_ChromaTex ("Chroma", 2D) = "gray" {}
		_Color ("Main Color", Vector) = (1,1,1,1)
		[Toggle(APPLY_GAMMA)] _ApplyGamma ("Apply Gamma", Float) = 0
		[Toggle(USE_YPCBCR)] _UseYpCbCr ("Use YpCbCr", Float) = 0
	}
	SubShader {
		LOD 100
		Tags { "QUEUE" = "Background" "RenderType" = "Opaque" }
		Pass {
			LOD 100
			Tags { "QUEUE" = "Background" "RenderType" = "Opaque" }
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 54303
			Program "vp" {
				SubProgram "d3d9 " {
					Keywords { "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 1, 0, -4, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    mov r0.xw, c4.x
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    mov r1.y, c4.y
					    slt r0.z, c0.x, r1.y
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c4.z, r0.y
					    mad r3.xzw, r0.x, c4.xyyy, c4.yyyx
					    mad o1.xy, v1, c2, c2.zwzw
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 21 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					div r1.x, cb1[6].y, cb1[6].x
					div r1.y, cb0[3].w, cb0[3].z
					lt r1.z, r1.x, r1.y
					div r0.xw, r1.xxxy, r1.yyyx
					movc r0.xy, r1.zzzz, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					mad o1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 1, 0, -4, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    mov r0.xw, c4.x
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    mov r1.y, c4.y
					    slt r0.z, c0.x, r1.y
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c4.z, r0.y
					    mad r3.xzw, r0.x, c4.xyyy, c4.yyyx
					    mad o1.xy, v1, c2, c2.zwzw
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 21 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					div r1.x, cb1[6].y, cb1[6].x
					div r1.y, cb0[3].w, cb0[3].z
					lt r1.z, r1.x, r1.y
					div r0.xw, r1.xxxy, r1.yyyx
					movc r0.xy, r1.zzzz, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					mad o1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 1, 0, -4, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    mov r0.xw, c4.x
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    mov r1.y, c4.y
					    slt r0.z, c0.x, r1.y
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c4.z, r0.y
					    mad r3.xzw, r0.x, c4.xyyy, c4.yyyx
					    mad o1.xy, v1, c2, c2.zwzw
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 21 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					div r1.x, cb1[6].y, cb1[6].x
					div r1.y, cb0[3].w, cb0[3].z
					lt r1.z, r1.x, r1.y
					div r0.xw, r1.xxxy, r1.yyyx
					movc r0.xy, r1.zzzz, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					mad o1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9VertexSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _MainTex_ST;
					//   float4 _MainTex_TexelSize;
					//   float4 _ProjectionParams;
					//   float4 _ScreenParams;
					//
					//
					// Registers:
					//
					//   Name               Reg   Size
					//   ------------------ ----- ----
					//   _ProjectionParams  c0       1
					//   _ScreenParams      c1       1
					//   _MainTex_ST        c2       1
					//   _MainTex_TexelSize c3       1
					//
					
					    vs_3_0
					    def c4, 1, 0, -4, 0
					    dcl_position v0
					    dcl_texcoord v1
					    dcl_position o0
					    dcl_texcoord o1.xy
					    mov r0.xw, c4.x
					    rcp r1.x, c1.x
					    mul r1.x, r1.x, c1.y
					    rcp r1.y, r1.x
					    rcp r1.z, c3.z
					    mul r1.z, r1.z, c3.w
					    mul r0.y, r1.y, r1.z
					    rcp r1.y, r1.z
					    slt r1.z, r1.x, r1.z
					    mul r0.z, r1.y, r1.x
					    lrp r2.xy, r1.z, r0.zwzw, r0
					    mul r0.xy, r2, v0
					    mov r1.y, c4.y
					    slt r0.z, c0.x, r1.y
					    mul r0.z, r0.z, r0.y
					    add r0.xy, r0, r0
					    mad r3.y, r0.z, c4.z, r0.y
					    mad r3.xzw, r0.x, c4.xyyy, c4.yyyx
					    mad o1.xy, v1, c2, c2.zwzw
					    mad o0.xy, r3.w, c255, r3
					    mov o0.zw, r3
					
					// approximately 21 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xy  
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[7], immediateIndexed
					dcl_input v0.xy
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mov r0.yz, l(0,1.000000,1.000000,0)
					div r1.x, cb1[6].y, cb1[6].x
					div r1.y, cb0[3].w, cb0[3].z
					lt r1.z, r1.x, r1.y
					div r0.xw, r1.xxxy, r1.yyyx
					movc r0.xy, r1.zzzz, r0.xyxx, r0.zwzz
					mul r0.xy, r0.xyxx, v0.xyxx
					add r0.xy, r0.xyxx, r0.xyxx
					lt r1.x, cb1[5].x, l(0.000000)
					movc r0.z, r1.x, -r0.y, r0.y
					mov r0.w, l(1.000000)
					mov o0.xyzw, r0.xzww
					mad o1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d9 " {
					Keywords { "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 1, 0, 0, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    texld_pp r0, v0, s0
					    mul_pp oC0.xyz, r0, c0
					    mov_pp oC0.w, c1.x
					
					// approximately 3 instruction slots used (1 texture, 2 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "APPLY_GAMMA_OFF" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					mul o0.xyz, r0.xyzx, cb0[4].xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c1, 0, -0.5, 1, 1.40199995
					    def c2, 1, -0.344139993, -0.714139998, 0
					    def c3, 1, 1.77199996, 0, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v0, s0
					    texld r1, v0, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c1.xyyw
					    dp2add r1.x, c1.zwzw, r0.xzzw, c1.x
					    dp3 r1.y, c2, r0
					    dp2add r1.z, c3, r0, c3.z
					    mul_pp oC0.xyz, r1, c0
					    mov_pp oC0.w, c1.z
					
					// approximately 11 instruction slots used (2 texture, 9 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "APPLY_GAMMA_OFF" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					sample r1.xyzw, v1.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r1.x, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					dp3 r1.y, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r1.z, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					mul o0.xyz, r1.xyzx, cb0[4].xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//
					
					    ps_3_0
					    def c1, 0.305306017, 0.682171106, 0.0125228781, 1
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    texld_pp r0, v0, s0
					    mad_pp r1.xyz, r0, c1.x, c1.y
					    mad_pp r1.xyz, r0, r1, c1.z
					    mul_pp r0.xyz, r0, r1
					    mul_pp oC0.xyz, r0, c0
					    mov_pp oC0.w, c1.w
					
					// approximately 6 instruction slots used (1 texture, 5 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "APPLY_GAMMA" "USE_YPCBCR_OFF" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					mad r1.xyz, r0.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r1.xyz, r0.xyzx, r1.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xyz, r0.xyzx, r1.xyzx
					mul o0.xyz, r0.xyzx, cb0[4].xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d9 " {
					Keywords { "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX9PixelSM30
					//
					// Generated by Microsoft (R) HLSL Shader Compiler 10.1
					//
					// Parameters:
					//
					//   sampler2D _ChromaTex;
					//   float4 _Color;
					//   sampler2D _MainTex;
					//
					//
					// Registers:
					//
					//   Name         Reg   Size
					//   ------------ ----- ----
					//   _Color       c0       1
					//   _MainTex     s0       1
					//   _ChromaTex   s1       1
					//
					
					    ps_3_0
					    def c1, 0, -0.5, 1, 1.40199995
					    def c2, 0.305306017, 0.682171106, 0, 0
					    def c3, 1, -0.344139993, -0.714139998, 0.0125228781
					    def c4, 1, 1.77199996, 0, 0
					    dcl_texcoord v0.xy
					    dcl_2d s0
					    dcl_2d s1
					    texld r0, v0, s0
					    texld r1, v0, s1
					    mov r0.yz, r1.xxww
					    add r0.xyz, r0, c1.xyyw
					    dp2add_pp r1.x, c1.zwzw, r0.xzzw, c1.x
					    dp3_pp r1.y, c3, r0
					    dp2add_pp r1.z, c4, r0, c4.z
					    mad_pp r0.xyz, r1, c2.x, c2.y
					    mad_pp r0.xyz, r1, r0, c3.w
					    mul_pp r0.xyz, r0, r1
					    mul_pp oC0.xyz, r0, c0
					    mov_pp oC0.w, c1.z
					
					// approximately 14 instruction slots used (2 texture, 12 arithmetic)"
				}
				SubProgram "d3d11 " {
					Keywords { "APPLY_GAMMA" "USE_YPCBCR" }
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xy
					dcl_output o0.xyzw
					dcl_temps 2
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					sample r1.xyzw, v1.xyxx, t1.xyzw, s1
					mov r0.yz, r1.xxwx
					add r0.xyz, r0.xyzx, l(0.000000, -0.500000, -0.500000, 0.000000)
					dp2 r1.x, l(1.000000, 1.402000, 0.000000, 0.000000), r0.xzxx
					dp3 r1.y, l(1.000000, -0.344140, -0.714140, 0.000000), r0.xyzx
					dp2 r1.z, l(1.000000, 1.772000, 0.000000, 0.000000), r0.xyxx
					mad r0.xyz, r1.xyzx, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
					mad r0.xyz, r1.xyzx, r0.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
					mul r0.xyz, r0.xyzx, r1.xyzx
					mul o0.xyz, r0.xyzx, cb0[4].xyzx
					mov o0.w, l(1.000000)
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}