namespace Tween
{
	public enum Ease
	{
		None = -1,
		Linear = 0,
		EaseInQuad = 1,
		EaseOutQuad = 2,
		EaseInOutQuad = 3,
		EaseOutInQuad = 4,
		EaseInCubic = 5,
		EaseOutCubic = 6,
		EaseInOutCubic = 7,
		EaseOutInCubic = 8,
		EaseInQuart = 9,
		EaseOutQuart = 10,
		EaseInOutQuart = 11,
		EaseOutInQuart = 12,
		EaseInQuint = 13,
		EaseOutQuint = 14,
		EaseInOutQuint = 15,
		EaseOutInQuint = 16,
		EaseInSine = 17,
		EaseOutSine = 18,
		EaseInOutSine = 19,
		EaseOutInSine = 20,
		EaseInExpo = 21,
		EaseOutExpo = 22,
		EaseInOutExpo = 23,
		EaseOutInExpo = 24,
		EaseInCirc = 25,
		EaseOutCirc = 26,
		EaseInOutCirc = 27,
		EaseOutInCirc = 28,
		EaseInElastic = 29,
		EaseOutElastic = 30,
		EaseInOutElastic = 31,
		EaseOutInElastic = 32,
		EaseInBack = 33,
		EaseOutBack = 34,
		EaseInOutBack = 35,
		EaseOutInBack = 36,
		EaseInBounce = 37,
		EaseOutBounce = 38,
		EaseInOutBounce = 39,
		EaseOutInBounce = 40,
	}
}
